name: CI

on:
  push:
    branches: main
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        openresty: [1.19.9.1]
        openssl: [1.1.1l]
    steps:
      - uses: actions/checkout@v2
      - name: Setup OpenResty
        uses: thibaultcha/setup-openresty@main
        with:
          version: ${{ matrix.openresty }}
          opt: --without-stream
          openssl-version: ${{ matrix.openssl }}
      - run: prove -r t/
